version: '3'
services:
  next-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    # 如果需要持久化数据，可以添加 volumes
    # volumes:
    #   - ./data:/app/data 